### ISSUE TITLE
Need help with yaml

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-DEPRECATED#5]
Not sure why this page will not show three people in one line (line three of images)

http://carpentries.org/#team

There are two files involved - `team.html` (in the `_includes` folder) and `_config.yml` in the main repo view of https://github.com/carpentries/carpentries.org

Any help appreciated - I have pasted completely plain text into the config file so not sure why this is happening - there are no special characters interfering as far as I know and the page builds without incident.

**Comment by rgaiacs** [comment]
From my knowledge, the loop implementation in https://github.com/carpentries/carpentries.org/blob/gh-pages/_includes/team.html#L12 to use [Bootstrap Grid Layout](http://getbootstrap.com/docs/4.0/layout/grid/#grid-options) is wrong. Each row has 12 virtual columns that you can merge to create the layout that you want but the sum of each column that you create **must** be equal to 12 virtual columns. For example,

~~~
            <div class="row">
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4">
                </div>
            </div>
~~~

is valid because 4 + 4 + 4 == 12 and

~~~
            <div class="row">
                <div class="col-sm-8">
                </div>
                <div class="col-sm-2">
                </div>
                <div class="col-sm-2">
                </div>
            </div>
~~~

is also valid because 8 + 2 + 2 == 12. But you should not use

~~~
            <div class="row">
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4">
                </div>
            </div>
~~~

because 4 + 4 != 12 neither you should use

~~~
            <div class="row">
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4">
                </div>
                <div class="col-sm-4">
                </div>
            </div>
~~~

because 4 + 4 + 4 + 4 != 12.

When redoing the for loop at https://github.com/carpentries/carpentries.org/blob/gh-pages/_includes/team.html#L12, you can use https://help.shopify.com/themes/liquid/objects/for-loops#forloop-index or https://help.shopify.com/themes/liquid/objects/for-loops#forloop-index0 to control when you need to create a new row.

All that I said so far, should be valid for Bootstrap v3.2.0. Please note that [Bootstrap](http://getbootstrap.com/) v4.0 was released and you might want to update to it.

**Comment by weaverbel** [comment]
Thanks @rgaiacs - I will see if I can fix it - I am not a Bootstrap wizard by any means but will see if I can make it work.

**Comment by weaverbel** [comment]
At least that gives me something to work on @rgaiacs

**Comment by weaverbel** [comment]
FIXED !!!!

**Comment by rgaiacs** [comment]
@weaverbel Could you point to the solution. This is good practice in the case that someone encounter the same problem in the future.
